name: runTests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create repository checkout
        uses: actions/checkout@v2

      - name: installing node
        uses: actions/setup-node@v2

      - name: installing dotenv
        run: npm install dotenv

      - name: Run tests in Chrome
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome TestCafe/*.test.js"
        
      - name: Run tests in Firefox
        uses: DevExpress/testcafe-action@latest
        with:
          args: "firefox TestCafe/*.test.js"
