name: runTests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-lastest]
    steps:
      - name: Create repository checkout
        uses: actions/checkout@v2

      - name: Run tests in Chrome
            uses: DevExpress/testcafe-action@latest
            with:
                args: "chrome ../../TestCafe/*.test.js"
        
      - name: Run tests in Firefox
            uses: DevExpress/testcafe-action@latest
            with:
                args: "firefox ../../TestCafe/*.test.js"
